name: sprint mission 1 PR Test

on:
  pull_request:
    branches:
      - 'part1-λ°±μ¬μ°-sprint1'
    paths:
      - 'codeit-bootcamp-spring/1-sprint-mission/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: β• JDK 17 μ„Έν…
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: β• gradlew μ‹¤ν–‰ κ¶ν• μ„¤μ •
        run: find . -name "gradlew" -exec chmod +x {} \;

      - name: π€ ν…μ¤νΈ μ§„ν–‰
        run: cd codeit-bootcamp-spring/1-sprint-mission && ./gradlew clean test